theme: jekyll-theme-cayman
title: Twitsnap Documentation
description: Documentation for the Twitsnap mobile App 
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
