theme: jekyll-theme-cayman
title: Twitsnap Documentation
description: Welcome to the documentation for the Twitsnap mobile app! 
plugins:
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - algo-feed-service
